### ISSUE TITLE
大佬，缺少文件了

### ISSUE THREAD

**Issue by CandyTek** [slkagura/RegEditor#1]
Can't load library: E:\Github\RegEditor\libjni\build\shared\libreg.debug.dll
java.lang.UnsatisfiedLinkError: Can't load library: E:\Github\RegEditor\libjni\build\shared\libreg.debug.dll
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at xyz.slkagura.reg.wrapper.JNI.<clinit>(JNI.kt:8)
	at MainTest.getUserPath(MainTest.kt:7)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by slkagura** [comment]
这个缺少文件是需要你用Clion打开libjni项目，先编译libjni得到dll，然后再使用
这个Demo当时随意写的，还没写完呢，晚点我补充一下

**Comment by slkagura** [comment]
> Can't load library: E:\Github\RegEditor\libjni\build\shared\libreg.debug.dll java.lang.UnsatisfiedLinkError: Can't load library: E:\Github\RegEditor\libjni\build\shared\libreg.debug.dll at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393) at java.base/java.lang.Runtime.load0(Runtime.java:755) at java.base/java.lang.System.load(System.java:1953) at xyz.slkagura.reg.wrapper.JNI.(JNI.kt:8) at MainTest.getUserPath(MainTest.kt:7) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

这个缺少文件是需要你用Clion打开libjni项目，先编译libjni得到dll，然后再使用
这个Demo当时随意写的，还没写完呢，晚点我补充一下

**Comment by CandyTek** [comment]
好的，谢谢大佬
